### ISSUE TITLE
[feature request] bam2wig.pl: Allow temporary files to be written to a temporary directory

### ISSUE THREAD

**Issue by balwierz** [tjparnell/biotoolbox#11]
bam2wig.pl produces temporary files (*temp.bin) in current directory. If the genome assembly has lots of contigs, there are lots of temporary files as well.

Issues with current behaviour:
* Before bam2wig.pl finishes the directory is filled with temp files.
* If bam2wig.pl is killed, these files will remain
* User might have a much faster local scratch filesystem
* tmp/scratch space normally would be cleaned of old files automatically

Proposed solutions:
* If defined, use $TMPDIR to store temporary files. If $TMPDIR is not set use current directory.
* Or allow user to explicitly specify the temporary directory. This might be better, because /tmp can be too small to hold wig files.

**Comment by tjparnell** [comment]
Hi Piotr,

Thanks for the suggestion. I’ve generally preferred keeping temp files locally (it’s actually based on the output name), rather than hiding them elsewhere in a tmp directory. When one fork dies on a specific contig, it’s nice to know which one. As you’ve pointed out, though, tmp can sometimes be a smallish partition that might not be ideal. But adding flexibility is certainly doable. I will also look into trapping errors and cleaning up automatically, although that might get tricky with forked processes.

Tim

**Comment by tjparnell** [comment]
This has been added to release 1.63. By default, all temp files are written to a temporary subdirectory in the output path, or to a user specified temp directory. If the script crashes for some reason, temp files will be left behind, but at least they will be contained within a temp directory. I've been using it for a while now, and it seems reliable.

**Comment by balwierz** [comment]
Thank you!
