### ISSUE TITLE
missing "use Statistics::Descriptive" and shift value being calculated despite --shiftval option

### ISSUE THREAD

**Issue by balwierz** [tjparnell/biotoolbox#9]
When running bam2wig.pl I am getting the following error:

> Can't locate object method "new" via package "Statistics::Descriptive::Sparse" (perhaps you forgot to load "Statistics::Descriptive::Sparse"?) at /usr/local/bin/bam2wig.pl line 887.

The output of the program is suggesting the shift value is being calculated despite `--shiftval` is explicitly given in the command line.

Command line:
`bam2wig.pl --position start --nope --shift --shiftval 4 --in in.bam --cpu 4 --nogz --out out.wig`

>  This program will convert bam alignments to wig data
 Calculating 3' shift value...
  sampling the top coverage regions on the largest 4 chromosomes...
   Forking into children for parallel scanning
   Scanning chr7, chr5, chr3, chr4
  0 regions found with a correlative shift in 0.2 minutes
Can't locate object method "new" via package "Statistics::Descriptive::Sparse" (perhaps you forgot to load "Statistics::Descriptive::Sparse"?) at /usr/local/bin/bam2wig.pl line 737.

(This file contains reads only from ONE strand, 0 regions is therefore expected)

However this line succeeded:
`perl -we 'require Statistics::Descriptive; my $stat = Statistics::Descriptive::Sparse->new;'`

Perl v5.26.0
Debian testing

**Comment by balwierz** [comment]
Adding `use Statistics::Descriptive;` in the beginning of bam2wig.pl removes the error message.

**Comment by tjparnell** [comment]
I do a lazy load of Statistics::Descriptive to avoid loading (or even requiring upon install) modules that are only required in some instances, which is why adding the use statement is a workaround. 

This was fixed in fe21d61 <https://github.com/tjparnell/biotoolbox/commit/fe21d61ee19a03bf4ca70dfd3c979093fd68d52f#diff-a811a291f2c8d0087eaad06168ea3f52>. I can replicate the issue in version 1.51, but not in 1.52. I’m preparing a new official release of 1.52 within days; it’s essentially done. If you pull the current master, it should be fixed. Please let me know if it’s not.

Tim
